export const TAGS = [
  'alternative education',
  'american education',
  'article about education',
  'articles on education',
  'bachelor of education',
  'bilingual education',
  'board of education',
  'character education',
  'college education',
  'community education',
  'continuing education',
  'deep learning',
  'degree',
  'dep ed',
  'department',
  'department of',
  'department of education',
  'department of education phone number',
  'department of state',
  'logo',
  'dept',
  'distance education',
  'doe',
  'edu',
  'educ',
  'education and training',
  'education articles',
  'education com',
  'education courses',
  'education degree',
  'education department',
  'education for all',
  'education fund',
  'education in america',
  'education logo',
  'education news',
  'education policy',
  'education portal',
  'education quotes',
  'education reform',
  'education system',
  'education USA',
  'education world',
  'educational games',
  'educational programs',
  'educational research',
  'educational resources',
  'educational sites',
  'educational websites',
  'educator',
  'educators school',
  'eduction',
  'elementary education',
  'free education',
  'further education',
  'general education',
  'global education',
  'higher education',
  'history of education',
  'home depot',
  'importance of education',
  'indian education system',
  'international education',
  'Keyword',
  'mathematics education',
  'meaning of education',
  'ministry of education',
  'ministry of education',
  'online education',
  'pe',
  'philosophy of education',
  'primary education',
  'public education',
  'public school',
  'quality education',
  'school',
  'school education',
  'school education department',
  'school of education',
  'schooling',
  'science education',
  'secondary education',
  'secretary of education',
  'special education',
  'state department',
  'state department of education',
  'teacher education',
  'teacher websites',
  'tertiary education',
  'university',
  'us department of education',
  'us education',
  'what is education',
  'www department of education',
  'www educ ar',
  'www education',
  'www education com',
  'www education portal',
  'www ministry of education'
];
